services:
  mc:
    image: ${MINECRAFT_REPO}:${JAVA_VER}
    env_file: ./.env
    ports:
      - 25565:25565
    volumes:
      - ${DATA}:/data
      - ${PLUGINS}:/plugins
    stdin_open: true
    tty: true
    restart: always
    healthcheck:
      test: mc-health
      start_period: 1m
      interval: 5s
      retries: 20
    networks:
      - mc-backend
volumes:
  data: {}
networks:
  mc-backend:
    external: true
